use crate::launch_options::model::*;
use once_cell::sync::Lazy;

/// The full launch-option catalog. Authored by hand from
/// `mxtools/apex启动项大全.txt` plus the user's CN-launcher defaults.
pub fn catalog() -> &'static LaunchOptionCatalog {
    &CATALOG
}

static CATALOG: Lazy<LaunchOptionCatalog> = Lazy::new(|| LaunchOptionCatalog {
    categories: vec![
        Category { id: "language",    label_zh: "语言与社区服" },
        Category { id: "display",     label_zh: "画面与分辨率" },
        Category { id: "window",      label_zh: "窗口模式" },
        Category { id: "performance", label_zh: "性能与优先级" },
        Category { id: "mouse",       label_zh: "鼠标输入" },
        Category { id: "audio",       label_zh: "音频" },
        Category { id: "hud",         label_zh: "调试与 HUD" },
        Category { id: "voice",       label_zh: "配音语言" },
    ],
    entries: vec![
        // ===== 语言与社区服 (defaults ON) =====
        OptionEntry {
            id: "language",
            category: "language",
            kind: OptionKind::Enum {
                flag: "-language",
                choices: &[
                    ("schinese", "简体中文"),
                    ("tchinese", "繁体中文"),
                    ("english",  "English"),
                ],
            },
            default_enabled: true,
            default_value: Some(OptionValue::Enum("schinese".into())),
            label_zh: "界面语言",
            description_zh: "社区服界面语言。默认简体中文。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "pylon_hostname",
            category: "language",
            kind: OptionKind::String {
                flag: "+pylon_matchmaking_hostname",
                placeholder: "r5r-org.sleep0.de",
            },
            default_enabled: true,
            default_value: Some(OptionValue::String("r5r-org.sleep0.de".into())),
            label_zh: "镜像服务器列表",
            description_zh: "Pylon 匹配服务器主机名。社区服默认使用 r5r-org.sleep0.de。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "notimeout",
            category: "language",
            kind: OptionKind::Toggle { args: &["-notimeout"] },
            default_enabled: false,
            default_value: None,
            label_zh: "无超时（防炸房挂）",
            description_zh: "禁用客户端超时检测。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "letterbox_threshold_zero",
            category: "language",
            kind: OptionKind::Toggle { args: &["+mat_letterbox_aspect_threshold", "0"] },
            default_enabled: false,
            default_value: None,
            label_zh: "社区服 4:3 全屏",
            description_zh: "社区服专用：移除 4:3 黑边。",
            risk: RiskLevel::Caution,
            conflicts_with: &[],
        },

        // ===== 画面与分辨率 =====
        OptionEntry {
            id: "resolution",
            category: "display",
            kind: OptionKind::IntPair { x_flag: "-w", y_flag: "-h" },
            default_enabled: false,
            default_value: Some(OptionValue::IntPair(1920, 1080)),
            label_zh: "强制分辨率",
            description_zh: "以启动项设置游戏内分辨率（如 1920x1080）。非原生分辨率可能导致游戏无法启动，必要时请先在显卡驱动中添加自定义分辨率。",
            risk: RiskLevel::Caution,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "letterbox_min_one",
            category: "display",
            kind: OptionKind::Toggle { args: &["+mat_letterbox_aspect_min", "1.0"] },
            default_enabled: false,
            default_value: None,
            label_zh: "4:3 移除黑边",
            description_zh: "配合 4:3 分辨率使用，移除黑边。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "wide_pillarbox",
            category: "display",
            kind: OptionKind::Toggle { args: &["+mat_wide_pillarbox", "0"] },
            default_enabled: false,
            default_value: None,
            label_zh: "超宽屏拉伸全屏",
            description_zh: "超宽屏显示器拉伸分辨率全屏。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "minimize_on_alt_tab",
            category: "display",
            kind: OptionKind::Toggle { args: &["+mat_minimize_on_alt_tab", "1"] },
            default_enabled: false,
            default_value: None,
            label_zh: "切屏最小化",
            description_zh: "类似 DX11 切屏让 apex 最小化。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },

        // ===== 窗口模式 =====
        OptionEntry {
            id: "fullscreen",
            category: "window",
            kind: OptionKind::Toggle { args: &["-fullscreen"] },
            default_enabled: false,
            default_value: None,
            label_zh: "全屏",
            description_zh: "以全屏模式启动游戏。",
            risk: RiskLevel::None,
            conflicts_with: &["window", "noborder"],
        },
        OptionEntry {
            id: "window",
            category: "window",
            kind: OptionKind::Toggle { args: &["-window"] },
            default_enabled: false,
            default_value: None,
            label_zh: "窗口",
            description_zh: "以窗口模式启动游戏。",
            risk: RiskLevel::None,
            conflicts_with: &["fullscreen"],
        },
        OptionEntry {
            id: "noborder",
            category: "window",
            kind: OptionKind::Toggle { args: &["-noborder"] },
            default_enabled: false,
            default_value: None,
            label_zh: "无边框",
            description_zh: "以无边框窗口启动（建议同时勾选「窗口」）。",
            risk: RiskLevel::None,
            conflicts_with: &["fullscreen"],
        },

        // ===== 性能与优先级 =====
        OptionEntry {
            id: "high_priority",
            category: "performance",
            kind: OptionKind::Toggle { args: &["-high"] },
            default_enabled: false,
            default_value: None,
            label_zh: "高线程优先级",
            description_zh: "将游戏线程优先级设置为高。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "fps_max",
            category: "performance",
            kind: OptionKind::Int { flag: "+fps_max", min: 0, max: 1000 },
            default_enabled: false,
            default_value: Some(OptionValue::Int(0)),
            label_zh: "锁定/解锁帧率",
            description_zh: "0 表示解锁；其他数字为上限（如 144）。",
            risk: RiskLevel::None,
            conflicts_with: &["no_render_on_input_thread"],
        },
        OptionEntry {
            id: "lobby_max_fps",
            category: "performance",
            kind: OptionKind::Int { flag: "+lobby_max_fps", min: 0, max: 1000 },
            default_enabled: false,
            default_value: Some(OptionValue::Int(0)),
            label_zh: "大厅帧率上限",
            description_zh: "0 表示解锁。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "no_render_on_input_thread",
            category: "performance",
            kind: OptionKind::Toggle { args: &["-no_render_on_input_thread"] },
            default_enabled: false,
            default_value: None,
            label_zh: "降低输入延迟",
            description_zh: "提高帧数（CPU≥6 核 + 高回报率外设推荐）。",
            risk: RiskLevel::Caution,
            conflicts_with: &["fps_max"],
        },

        // ===== 鼠标输入 =====
        OptionEntry {
            id: "noforcemspd",
            category: "mouse",
            kind: OptionKind::Toggle { args: &["-noforcemspd"] },
            default_enabled: false,
            default_value: None,
            label_zh: "保留鼠标速度",
            description_zh: "使用原始鼠标速度。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "noforcemaccel",
            category: "mouse",
            kind: OptionKind::Toggle { args: &["-noforcemaccel"] },
            default_enabled: false,
            default_value: None,
            label_zh: "保留加速曲线",
            description_zh: "保留原始加速曲线。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "noforcemparms",
            category: "mouse",
            kind: OptionKind::Toggle { args: &["-noforcemparms"] },
            default_enabled: false,
            default_value: None,
            label_zh: "保留自定义鼠标参数",
            description_zh: "不覆盖用户自定义参数。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },

        // ===== 音频 =====
        OptionEntry {
            id: "miles_channels",
            category: "audio",
            kind: OptionKind::Enum {
                flag: "+miles_channels",
                choices: &[
                    ("2", "立体声 (2)"),
                    ("8", "7.1 声道 (8)"),
                ],
            },
            default_enabled: false,
            default_value: Some(OptionValue::Enum("2".into())),
            label_zh: "声道数",
            description_zh: "音频输出声道。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },

        // ===== 调试与 HUD =====
        OptionEntry {
            id: "showpos",
            category: "hud",
            kind: OptionKind::Toggle { args: &["+cl_showpos", "1"] },
            default_enabled: false,
            default_value: None,
            label_zh: "显示位置/角度/速度",
            description_zh: "在游戏中显示名称、位置、角度和速度。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "showfps",
            category: "hud",
            kind: OptionKind::Toggle { args: &["+cl_showfps", "1"] },
            default_enabled: false,
            default_value: None,
            label_zh: "显示 FPS / 网络",
            description_zh: "显示性能与网络参数。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "skip_intro",
            category: "hud",
            kind: OptionKind::Toggle { args: &["-novid"] },
            default_enabled: false,
            default_value: None,
            label_zh: "跳过开场动画",
            description_zh: "省去开场视频，约快 5 秒。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "fov_scale",
            category: "hud",
            kind: OptionKind::Toggle { args: &["+cl_fovScale", "1.7"] },
            default_enabled: false,
            default_value: None,
            label_zh: "强制 120 FOV",
            description_zh: "强制更宽的视野。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
        OptionEntry {
            id: "softened_locale",
            category: "hud",
            kind: OptionKind::Toggle { args: &["+cl_is_softened_locale", "1"] },
            default_enabled: false,
            default_value: None,
            label_zh: "击杀血雾改红光",
            description_zh: "中文版默认效果。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },

        // ===== 配音语言 =====
        OptionEntry {
            id: "miles_language",
            category: "voice",
            kind: OptionKind::Enum {
                flag: "+miles_language",
                choices: &[
                    ("mandarin", "中文配音"),
                    ("english",  "英文配音"),
                    ("japanese", "日文配音（需额外语音包）"),
                ],
            },
            default_enabled: false,
            default_value: Some(OptionValue::Enum("english".into())),
            label_zh: "配音语言",
            description_zh: "更改游戏内角色配音。",
            risk: RiskLevel::None,
            conflicts_with: &[],
        },
    ],
});
